### ISSUE TITLE
Help with LicenseExpressionAlongWithOthersException

### ISSUE THREAD

**Issue by villaflaminio** [CycloneDX/cyclonedx-python#826] opened 2024-11-08 16:12 UTC
Hi 
I am experiencing an ambiguous case related to [this issue](https://github.com/CycloneDX/specification/pull/205) .

The `LicenseExpressionAlongWithOthersException` is thrown if we have a `LicenseExpression` from a Python package and use the `--gather-license-texts` option at the same time.

Step to reproduce :
```
python3 -m venv venv_dependencies
python3 -m venv venv_cyclonedx

source venv_dependencies/bin/activate
pip install cryptography==43.0.1
deactivate

source venv_cyclonedx/bin/activate
pip install cyclonedx-bom==5.1.0
cyclonedx-py environment --PEP-639 --gather-license-texts -o cyclonedx-bom.json --sv 1.6 --of JSON venv_dependencies
```
Error:
```
CRITICAL | CDX > Found LicenseExpression along with others licenses in: <Component bom-ref=<BomRef 'cryptography==43.0.1' id=140025822015568>, group=None, name=cryptography, version=43.0.1, type=ComponentType.LIBRARY>
```
In the case of not including the `--gather-license-texts` option, it works perfectly!

Taking a closer look at what happens before the exception is raised [there](https://github.com/CycloneDX/cyclonedx-python-lib/blob/5788bc13c0a0622f18264493158a9742945fbeeb/cyclonedx/model/bom.py#L720) , this is the element content:
![Image](https://github.com/user-attachments/assets/b6708b3b-056b-4c8d-9ed5-332b5049cf3c)
How do you recommend handling this situation? Thank you for your support!

**Comment by jkowalleck** [comment] 2024-11-08 16:17
Thanks for reporting this.

this appears to be an unintended behaviour. 

@villaflaminio , Could you help me craft a reproducible environment for this? 
Could you publish a github repository that could be used as a test subject?

**Comment by jkowalleck** [comment] 2024-11-08 16:20
A practical solution, i'd imagine:
if the declared licence is an expression, then all declared licence files are used as licence evidence, instead of an expression.

**Comment by jkowalleck** [comment] 2024-11-08 16:45
the thing is: the spec does not allow a mix of expression and named/id-licenses, yet.
see https://github.com/CycloneDX/specification/issues/454

**Comment by jkowalleck** [comment] 2024-11-08 16:49
> What kind of repository do you need? What do I need to include?

@villaflaminio, no additional information needed.


----

for reprocusing: run analysis on `cryptography==43.0.1`.
this is to be fixed in all implemented collectors: `pypoject.toml` and environment analysis.

**Comment by villaflaminio** [comment] 2024-11-08 17:42
Honestly, I can't think of "a clean way" to include this information without breaking the specification (especially according with the [#454](https://github.com/CycloneDX/specification/issues/454)).
I note that from the specification we do not even have the ‘Properties’ field available if we are talking about a ‘Licence Expression’; otherwise we could have added the text of the license files there, to ‘support’ the expression.
Do I like it? Absolutely not!

**Comment by jkowalleck** [comment] 2024-11-08 17:48
here is a possible solution: 
https://github.com/CycloneDX/cyclonedx-python/issues/826#issuecomment-2465195711

**Closed** 2024-11-09 13:18 UTC
Labels: bug, source: environment

**Comment by jkowalleck** [comment] 2024-11-09 13:50
a fix was published via https://github.com/CycloneDX/cyclonedx-python/releases/tag/v5.1.1
