### ISSUE TITLE
feat: clean license doubles

### ISSUE THREAD

**Issue by andife** [CycloneDX/cyclonedx-python#571] opened 2023-08-29 15:32 UTC
Hi,
I wonder if there are tools possibilities to clean up (or even merge) the generated cyclonedx-files a bit...

my generated file contains the following fragments:

e.g. [{'license': {'name': 'Apache 2.0'}}, {'license': {'name': 'Apache Software License'}}]
or 
[{'license': {'name': 'MIT'}}, {'license': {'name': 'MIT License'}}]
or
[{'license': {'name': 'MPL-2.0'}}, {'license': {'name': 'Mozilla Public License 2.0 (MPL 2.0)'}}] 

In my case one entry would be enough for me... Best would be the "SPDX ID"

**Comment by jkowalleck** [comment] 2023-08-30 06:11
The requested features should be fixed in the release of the upcoming version 4 of this tool.

**Comment by andife** [comment] 2023-08-30 09:14
Hi, I wonder how that works?

I checked out the branch https://github.com/CycloneDX/cyclonedx-python/tree/dev/4.x.x and installed it with pip install -e . A build of sbom with version 4 with the option "-e" still gives me the exact number of corresponding multiple entries (does not matter the version).

The packages are for example: tqdm, toml, scipy, prometheus-client, opencv-python, PyYAML

**Comment by jkowalleck** [comment] 2023-08-30 09:17
thank you for the report.

> The requested features should be fixed in the release of the upcoming version 4 of this tool.

should ... 
maybe it is broken. 


issue was reopened for further investigation.

**Comment by jkowalleck** [comment] 2023-08-30 09:18
@andife , could you provide a reproducible setup? for testing purposes
which steps need to be dine to reproduce your results?

**Comment by andife** [comment] 2023-08-30 12:39
Yes, I made an github workflow to demonstrate that behavoir.
https://github.com/andife/cyclonedx-python/blob/test_spdxy/.github/workflows/test_spdx.yml

The results / artifacts, two json spdx-files could be found at 
https://github.com/andife/cyclonedx-python/actions/runs/6024699313

Comparing the two results, the number of entrys is exactly the same:

![image](https://github.com/CycloneDX/cyclonedx-python/assets/20612932/03f5e26c-be62-4cfc-8e03-724f84d3e64e)

**Comment by jkowalleck** [comment] 2023-08-31 06:07
found some "doubled" licenses: 
```json
    {
      "author": "Jeff Forcier",
      "bom-ref": "116dab0b-5e60-480a-bbc2-49bfacc90686",
      "licenses": [
        { "license": { "name": "BSD" } },
        { "license": { "name": "BSD License" } }
      ],
      "name": "invoke",
      "purl": "pkg:pypi/invoke@1.7.3",
      "type": "library",
      "version": "1.7.3"
    }
```
found the SPDX detection still not working

**Comment by jkowalleck** [comment] 2023-08-31 06:14
proper SPDX licen detection is a feature of #459 
this issue should be a bugfix for the duplicates

**Comment by jkowalleck** [comment] 2023-08-31 09:54
after https://github.com/CycloneDX/cyclonedx-python/issues/459 was implemented,
it will still happen that some licenses are duplicate, since there is no fuzzy detection for license names, yet

**Comment by jkowalleck** [comment] 2023-08-31 10:19
remember: the "license" field may dome from multiple sources:
- package metadata licenses - see https://packaging.python.org/en/latest/specifications/core-metadata/#license 
- package license trove classifier - see https://pypi.org/classifiers/ 

they solve different purposes, and one allows free text ...

**Comment by jkowalleck** [comment] 2023-09-06 11:11
Cleaning the license doubles will not happen, sorry. some of the information is sourced from a free text where package authors may write whatever they want.


The SPDX ids are mapped correctly now, thanks to #576.
The SPDX expressions are detected correctly now, thanks to  #578

**Closed by jkowalleck** 2023-09-06 11:11 UTC
Labels: enhancement
